import React from "react";
import { Badge, Text, makeStyles, tokens } from "@fluentui/react-components";
import type { Json } from "@gik/kernel";
import { runDeclarativeValidators } from "@gik/evaluators";
import type { ProjectionView } from "@gik/react";

import { defineComponent, trialNode, type ComponentDescription, type ComponentValidationReport } from "../../shared/definition";
import { componentRootProps, componentStylePropsSchema, readPath, records, textAt } from "../../shared/component";

export const CHART_SEMANTIC_TOKENS = ["accent", "positive", "negative", "warning", "neutral"] as const;
export const CHART_VARIANTS = ["standard", "compact"] as const;
export const CHART_KINDS = ["bar", "line", "pie"] as const;
type ChartToken = typeof CHART_SEMANTIC_TOKENS[number];
const schema = {
  $schema: "http://json-schema.org/draft-07/schema#", type: "object", additionalProperties: false, required: ["points", "spec"],
  properties: { ...componentStylePropsSchema, points: { type: "array", items: { type: "object" } }, summaryValue: { type: ["string", "number"] }, variant: { enum: CHART_VARIANTS }, spec: { type: "object", additionalProperties: false, required: ["kind", "fields"], properties: {
    kind: { enum: CHART_KINDS }, title: { type: "string" }, description: { type: "string" }, emptyText: { type: "string" }, valueSuffix: { type: "string" }, fields: { type: "object", additionalProperties: false, required: ["label", "value"], properties: { label: { type: "string", minLength: 1 }, value: { type: "string", minLength: 1 }, tone: { type: "string", minLength: 1 } } }, toneMap: { type: "object", additionalProperties: { enum: CHART_SEMANTIC_TOKENS } },
    summary: { type: "object", additionalProperties: false, required: ["label"], properties: { label: { type: "string", minLength: 1 }, prefix: { type: "string" }, suffix: { type: "string" } } },
    table: { type: "object", additionalProperties: false, required: ["label", "columns"], properties: { label: { type: "string", minLength: 1 }, columns: { type: "array", minItems: 1, items: { type: "object", additionalProperties: false, required: ["field", "label"], properties: { field: { type: "string", minLength: 1 }, label: { type: "string", minLength: 1 }, prefix: { type: "string" }, suffix: { type: "string" } } } } } },
  } } },
} as const;
type ChartTableColumn = { field: string; label: string; prefix?: string; suffix?: string };
type ChartSpec = { kind: typeof CHART_KINDS[number]; title?: string; description?: string; emptyText?: string; valueSuffix?: string; fields: { label: string; value: string; tone?: string }; toneMap?: Record<string, ChartToken>; summary?: { label: string; prefix?: string; suffix?: string }; table?: { label: string; columns: ChartTableColumn[] } };
const useStyles = makeStyles({ root: { display: "grid", gap: tokens.spacingVerticalM, minWidth: 0 }, header: { display: "grid", gap: tokens.spacingVerticalXXS }, description: { color: tokens.colorNeutralForeground3 }, summary: { display: "grid", gap: tokens.spacingVerticalXXS }, chart: { width: "100%", minWidth: 0, overflow: "visible" }, legend: { display: "flex", flexWrap: "wrap", gap: tokens.spacingHorizontalS }, legendItem: { display: "flex", alignItems: "center", gap: tokens.spacingHorizontalXS }, swatch: { width: tokens.spacingHorizontalM, height: tokens.spacingVerticalM, borderRadius: tokens.borderRadiusSmall }, tableWrap: { overflowX: "auto" }, table: { width: "100%", borderCollapse: "collapse" }, cell: { padding: `${tokens.spacingVerticalS} ${tokens.spacingHorizontalS}`, textAlign: "left", borderBottom: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke2}`, whiteSpace: "nowrap" } });
function fill(token: ChartToken | undefined): string { if (token === "positive") return tokens.colorPaletteGreenForeground1; if (token === "negative") return tokens.colorPaletteRedForeground1; if (token === "warning") return tokens.colorPaletteDarkOrangeForeground1; if (token === "neutral") return tokens.colorNeutralForeground3; return tokens.colorBrandForeground1; }
const categoricalFills = [tokens.colorBrandForeground1, tokens.colorPaletteGreenForeground1, tokens.colorPaletteDarkOrangeForeground1, tokens.colorPaletteRedForeground1, tokens.colorPaletteLightTealForeground2];
function pieSlicePath(centerX: number, centerY: number, radius: number, startAngle: number, endAngle: number): string {
  const point = (angle: number) => ({ x: centerX + radius * Math.cos(angle), y: centerY + radius * Math.sin(angle) });
  const start = point(startAngle); const end = point(endAngle); const largeArc = endAngle - startAngle > Math.PI ? 1 : 0;
  return `M ${centerX} ${centerY} L ${start.x} ${start.y} A ${radius} ${radius} 0 ${largeArc} 1 ${end.x} ${end.y} Z`;
}
export const Chart: ProjectionView = ({ node }) => {
  const styles = useStyles(); const points = records(node.props.points); const spec = (node.props.spec ?? {}) as ChartSpec; const compact = (node.props.variant ?? "standard") === "compact";
  const values = points.map((point) => Number(readPath(point, spec.fields?.value))).filter(Number.isFinite); const max = Math.max(...values, 0);
  if (!spec.fields || points.length === 0 || max <= 0) return <Text {...componentRootProps(node)}>{spec.emptyText ?? "No chart data available."}</Text>;
  const width = 640; const height = compact ? 180 : 260; const left = 42; const top = 16; const bottom = compact ? 30 : 48; const plotHeight = height - top - bottom; const step = (width - left - 12) / points.length;
  const coordinates = points.map((point, index) => { const value = Number(readPath(point, spec.fields.value)); return { point, value, x: left + step * index + step / 2, y: top + plotHeight - (value / max) * plotHeight }; });
  const total = coordinates.reduce((sum, entry) => sum + entry.value, 0); let pieAngle = -Math.PI / 2;
  const formatCell = (point: Record<string, unknown>, column: ChartTableColumn) => `${column.prefix ?? ""}${textAt(point, column.field)}${column.suffix ?? ""}`;
  return <figure {...componentRootProps(node, styles.root)} aria-label={spec.title ?? "Chart"}><figcaption className={styles.header}>{spec.title ? <Text weight="semibold" size={500}>{spec.title}</Text> : null}{spec.description ? <Text className={styles.description}>{spec.description}</Text> : null}{spec.summary ? <div className={styles.summary} role="group" aria-label={spec.summary.label}><Text>{spec.summary.label}</Text><Text weight="bold" size={700}>{spec.summary.prefix ?? ""}{String(node.props.summaryValue ?? "")}{spec.summary.suffix ?? ""}</Text></div> : null}</figcaption><svg className={styles.chart} viewBox={`0 0 ${width} ${height}`} role="img"><title>{spec.title ?? "Chart"}</title><desc>{spec.description ?? `${spec.kind} chart with ${points.length} points`}</desc>{spec.kind !== "pie" ? <line x1={left} y1={top + plotHeight} x2={width - 12} y2={top + plotHeight} stroke={tokens.colorNeutralStroke1} /> : null}
    {spec.kind === "line" ? <polyline points={coordinates.map(({ x, y }) => `${x},${y}`).join(" ")} fill="none" stroke={tokens.colorBrandForeground1} strokeWidth={tokens.strokeWidthThicker} /> : null}
    {coordinates.map(({ point, value, x, y }, index) => { const toneValue = textAt(point, spec.fields.tone); const mappedToken = toneValue ? spec.toneMap?.[toneValue] : undefined; const color = mappedToken ? fill(mappedToken) : categoricalFills[index % categoricalFills.length]; const label = textAt(point, spec.fields.label); if (spec.kind === "pie") { const startAngle = pieAngle; const endAngle = pieAngle + (value / total) * Math.PI * 2; pieAngle = endAngle; return <path key={`${label}-${index}`} d={pieSlicePath(width / 2, height / 2, compact ? 72 : 106, startAngle, endAngle)} fill={color} stroke={tokens.colorNeutralBackground1} strokeWidth={tokens.strokeWidthThick}><title>{`${label}: ${value}${spec.valueSuffix ?? ""}`}</title></path>; } return <g key={`${label}-${index}`}>{spec.kind === "bar" ? <rect x={x - step * 0.3} y={y} width={step * 0.6} height={top + plotHeight - y} rx={tokens.borderRadiusSmall} fill={color}><title>{`${label}: ${value}${spec.valueSuffix ?? ""}`}</title></rect> : <circle cx={x} cy={y} r="5" fill={color}><title>{`${label}: ${value}${spec.valueSuffix ?? ""}`}</title></circle>}<text x={x} y={height - (compact ? 10 : 22)} textAnchor="middle" fill={tokens.colorNeutralForeground2} fontSize={tokens.fontSizeBase200}>{label}</text>{!compact ? <text x={x} y={Math.max(y - 8, 12)} textAnchor="middle" fill={tokens.colorNeutralForeground1} fontSize={tokens.fontSizeBase200}>{value}{spec.valueSuffix ?? ""}</text> : null}</g>; })}
  </svg><div className={styles.legend} aria-hidden="true">{coordinates.map(({ point, value }, index) => { const toneValue = textAt(point, spec.fields.tone); const mappedToken = toneValue ? spec.toneMap?.[toneValue] : undefined; const color = mappedToken ? fill(mappedToken) : categoricalFills[index % categoricalFills.length]; return <div className={styles.legendItem} key={index}><span className={styles.swatch} style={{ backgroundColor: color }} /><Badge appearance="outline">{textAt(point, spec.fields.label)}{spec.kind === "pie" ? ` · ${value}${spec.valueSuffix ?? ""}` : ""}</Badge></div>; })}</div>{spec.table ? <div className={styles.tableWrap}><table className={styles.table} aria-label={spec.table.label}><thead><tr>{spec.table.columns.map((column) => <th className={styles.cell} key={column.field}>{column.label}</th>)}</tr></thead><tbody>{points.map((point, rowIndex) => <tr key={`${textAt(point, spec.fields.label)}-${rowIndex}`}>{spec.table!.columns.map((column) => <td className={styles.cell} key={column.field}>{formatCell(point, column)}</td>)}</tr>)}</tbody></table></div> : null}</figure>;
};
const description: ComponentDescription = { capability: "primitive:chart", summary: "Renders a small mapped numeric series as an accessible bar, line, or pie chart.", dataProp: "points", events: [], semanticTokens: CHART_SEMANTIC_TOKENS, defaultVariant: "standard", variants: [{ value: "standard", summary: "Full chart with direct value labels where the chart kind supports them.", useWhen: ["The chart is a primary analytical surface", "Exact values should remain visible"] }, { value: "compact", summary: "Reduced-height chart without direct value labels.", useWhen: ["The chart supports a dashboard summary", "Vertical space is constrained"] }], authoring: { useWhen: ["Numeric values need visual comparison, trend reading, or part-to-whole analysis", "A small single series is sufficient"], avoidWhen: ["Values are primarily read as exact measures; use measure-set", "The data needs multi-series interaction or zooming; use a specialized chart capability"], rules: ["Provide finite non-negative numeric values", "Set spec.kind to bar for category comparison, line for ordered trends, or pie for part-to-whole composition", "Keep labels short", "Map tone values only to recognized chart tokens"] } };
export function describeChart() { return description; }
export function getChartSchema(): Record<string, unknown> { return schema as unknown as Record<string, unknown>; }
export function validateChart(props: unknown): ComponentValidationReport { return runDeclarativeValidators([
  { kind: "ajv-schema", schema: getChartSchema(), message: "Invalid primitive:chart props", code: "primitive-chart-schema" },
  { kind: "jsonata", expr: "($field := data.spec.fields.value; $count(data.points[$type($lookup($, $field)) = 'number' and $lookup($, $field) >= 0]) = $count(data.points))", message: "Chart values must be finite non-negative numbers", code: "semantic-chart-values" },
], props as Json); }
export function materializeChartTrial() { return trialNode("primitive:chart", { variant: "standard", points: [{ hour: "08:00", count: 7, posture: "normal" }, { hour: "09:00", count: 18, posture: "elevated" }, { hour: "10:00", count: 31, posture: "critical" }, { hour: "11:00", count: 12, posture: "normal" }], spec: { kind: "line", title: "Risk events by hour", description: "Observed events during the response window", fields: { label: "hour", value: "count", tone: "posture" }, toneMap: { normal: "accent", elevated: "warning", critical: "negative" } } }); }
export const chartDefinition = defineComponent({ description, version: "1.1.0", component: Chart, getSchema: getChartSchema, validate: validateChart, materializeTrial: materializeChartTrial });